import { useTheme } from 'next-themes'
import Head from 'next/head'
import { useState, useEffect } from 'react';
import About from '../components/About';
import Footer from '../components/Footer';
import Nav from '../components/Nav';
import Projects from '../components/Projects';
import SideNav from '../Components/SideNav';




export default function Home() {
  const {theme, setTheme} = useTheme();
  const[burger, setBurger] = useState(false)
  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), [])
  if(!mounted){
    return null
  }
  return (
    <div className=''>
      <Head>
        <title>Shittu Adewale</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Nav burger={burger} setBurger={setBurger} theme={theme} setTheme={setTheme} />
     <SideNav burger={burger}/>
      <About />
      <Projects />
      <Footer />



     
    </div>
  )
}
